### ISSUE TITLE
mbed compile fails

### ISSUE THREAD

**Issue by sagr4019** [OpenNuvoton/NuMaker-mbed-TZ-nonsecure-example#2]
Hi,
This example don't create successfully a hex file.
I followed each step in the Readme.md.

My configuration:
Windows 10 64bit
mbed-cli 1.8.3

mbed compile -m NUMAKER_PFM_M2351 -t ARMC6 -v
[mbed] Working path "C:\NuMaker-mbed-TZ-secure-example" (program)
[mbed] Exec "C:\Python27\python.exe -u C:\NuMaker-mbed-TZ-secure-example\mbed-os\tools\make.py -t ARMC6 -m NUMAKER_PFM_M2351 --source . --build .\BUILD\NUMAKER_PFM_M2351\ARMC6 -v" in "C:\NuMaker-mbed-TZ-secure-example"
Building project NuMaker-mbed-TZ-secure-example (NUMAKER_PFM_M2351, ARMC6)
Scan: NuMaker-mbed-TZ-secure-example
Scan: env
Using ROM region application in this build.
  Region application: size 0x40000, offset 0x0
Using RAM region application_ram in this build.
  Region application_ram: size 0x8000, offset 0x20000000
Macros: -DTARGET_M2351KIAAEES -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -DTARGET_LIKE_MBED -DMBED_BUILD_TIMESTAMP=1555014024.19 -DDEVICE_PORTINOUT=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_RTC=1 -D__CMSIS_RTOS -DTOOLCHAIN_ARMC6 -DTARGET_FLASH_CMSIS_ALGO -D__CORTEX_M23 -DDEVICE_I2C_ASYNCH=1 -DTARGET_CORTEX_M -DDEVICE_PORTOUT=1 -DDEVICE_LPTICKER=1 -DTARGET_NUVOTON -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 -DTARGET_NUMAKER_PFM_M2351 -DTARGET_M23 -DDEVICE_SPI_ASYNCH=1 -DTARGET_RELEASE -DTARGET_LIKE_CORTEX_M23 -DDEVICE_USTICKER=1 -DTARGET_M2351 -DDEVICE_PORTIN=1 -DDEVICE_SLEEP=1 -DMBED_FAULT_HANDLER_DISABLED -DDEVICE_SPI=1 -DARM_MATH_ARMV8MBL -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_PWMOUT=1 -DLPTICKER_DELAY_TICKS=3 -DMBED_TZ_DEFAULT_ACCESS=1 -DDEVICE_FLASH=1 -DTOOLCHAIN_ARM -DTOOLCHAIN_ARM_STD
Link: NuMaker-mbed-TZ-secure-example_application
Link: C:\Keil_v5\ARM\ARMCLANG\bin\armlink --via .\BUILD\NUMAKER_PFM_M2351\ARMC6\.link_options.txt
[DEBUG] Return: 1
[DEBUG] Errors: Warning: L3912W: Option 'legacyalign' is deprecated.
[DEBUG] Errors: armclang.exe: error: ARMv4 is not supported by this toolchain
[DEBUG] Errors: armclang.exe: note:
[DEBUG] Errors: Check that your license details are correct in the License Management dialog of MDK. Additional information is available at:
[DEBUG] Errors:  http://www.keil.com/support/man/docs/license/license_management.htm
[DEBUG] Errors:  If you need further help, provide this complete error report to your supplier or license.support@arm.com.
[DEBUG] Errors:  - ARMLMD_LICENSE_FILE: unset
[DEBUG] Errors:  - LM_LICENSE_FILE: unset
[DEBUG] Errors:  - ARM_TOOL_VARIANT: unset
[DEBUG] Errors:  - ARM_PRODUCT_PATH: unset
[DEBUG] Errors:  - Product location: C:\Keil_v5\ARM\sw\mappings
[DEBUG] Errors:  - Toolchain location: C:\Keil_v5\ARM\ARMCLANG\bin
[DEBUG] Errors:  - Selected tool variant: mdk_cm0_cm23
[DEBUG] Errors: Product: MDK Cortex-M0/M23 for Nuvoton 5.26
[DEBUG] Errors: Component: ARM Compiler 6.10.1
[DEBUG] Errors: Tool: armclang [5d143200]
[DEBUG] Errors:
[DEBUG] Errors: armclang.exe: error: ARM Compiler does not support '--target=arm-arm-none-eabi'
[DEBUG] Errors: Error: L6636E: Pre-processor step failed for './BUILD/NUMAKER_PFM_M2351/ARMC6/.link_script.sct'
[DEBUG] Errors: Error: L6372E: Image needs at least one load region.
[DEBUG] Errors: Not enough information to list the image map.
[DEBUG] Errors: Finished: 1 information, 1 warning and 2 error messages.
Traceback (most recent call last):
  File "C:\NuMaker-mbed-TZ-secure-example\mbed-os\tools\make.py", line 293, in <module>
    ignore=options.ignore
  File "C:\NuMaker-mbed-TZ-secure-example\mbed-os\tools\build_api.py", line 542, in build_project
    binary, _ = toolchain.link_program(resources, build_path, name + "_application")
  File "C:\NuMaker-mbed-TZ-secure-example\mbed-os\tools\toolchains\__init__.py", line 633, in link_program
    self.link(elf, objects, libraries, lib_dirs, linker_script)
  File "C:\NuMaker-mbed-TZ-secure-example\mbed-os\tools\hooks.py", line 34, in wrapper
    res = function(t_self, *args, **kwargs)
  File "C:\NuMaker-mbed-TZ-secure-example\mbed-os\tools\toolchains\arm.py", line 294, in link
    self.default_cmd(cmd)
  File "C:\NuMaker-mbed-TZ-secure-example\mbed-os\tools\toolchains\__init__.py", line 662, in default_cmd
    raise ToolException(_stderr)
ToolException: Warning: L3912W: Option 'legacyalign' is deprecated.
armclang.exe: error: ARMv4 is not supported by this toolchain
Check that your license details are correct in the License Management dialog of MDK. Additional information is available at:
 http://www.keil.com/support/man/docs/license/license_management.htm
 If you need further help, provide this complete error report to your supplier or license.support@arm.com.
 - ARMLMD_LICENSE_FILE: unset
 - LM_LICENSE_FILE: unset
 - ARM_TOOL_VARIANT: unset
 - ARM_PRODUCT_PATH: unset
 - Product location: C:\Keil_v5\ARM\sw\mappings
 - Toolchain location: C:\Keil_v5\ARM\ARMCLANG\bin
 - Selected tool variant: mdk_cm0_cm23
Product: MDK Cortex-M0/M23 for Nuvoton 5.26
Component: ARM Compiler 6.10.1
Tool: armclang [5d143200]

armclang.exe: error: ARM Compiler does not support '--target=arm-arm-none-eabi'
Error: L6636E: Pre-processor step failed for './BUILD/NUMAKER_PFM_M2351/ARMC6/.link_script.sct'
Error: L6372E: Image needs at least one load region.
Not enough information to list the image map.
Finished: 1 information, 1 warning and 2 error messages.

[mbed] ERROR: "C:\Python27\python.exe" returned error.
       Code: 1
       Path: "C:\NuMaker-mbed-TZ-secure-example"
       Command: "C:\Python27\python.exe -u C:\NuMaker-mbed-TZ-secure-example\mbed-os\tools\make.py -t ARMC6 -m NUMAKER_PFM_M2351 --source . --build .\BUILD\NUMAKER_PFM_M2351\ARMC6 -v"
       Tip: You could retry the last command with "-v" flag for verbose output
---

**Comment by cyliangtw** [comment]
It's your local Keil ARMC6 compiler license issue.
For free ARMC6 compiler, Mbed-studio is a good choice. mbed-studio [download URL.](https://os.mbed.com/docs/mbed-os/v5.8/tools/arm-mbed-studio.html)
After finish Mbed-studio installation, you just OpenWorkSpace and browse your local TZ-nosecure-example.
Then to choose M2351 in the Target drop-down list before build.
Remind, you need to build TZ-secure-example in advance.

**Comment by cyliangtw** [comment]
@sagr4019 , for 1st trial run, mbed-os-example-blinky is easier practice, you could git clone mbed-os-example-blinky, then  `git checkout mbed-os-5.11.5` . To build  this sample by Mbed-studio or by CLI.
Before burn blinky hex, please drag & drop default secure image from `\\mbed-os\targets\TARGET_NUVOTON\TARGET_M2351\TARGET_NUMAKER_PFM_M2351\TARGET_M23_NS`
